# Based on:
# https://docs.travis-ci.com/user/languages/android#CI-Environment-for-Android-Projects
# https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
language: android
android:
  components:
    - tools
    - platform-tools-24.0.2
    - build-tools-26.0.2
    - android-24
    - extra-android-m2repository
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8

script:
   - ./gradlew assembleDebug testOnlineDebugUnitTest testOfflineDebugUnitTest checkstyle
     # build  # Would try need the online version, that seems to need fabric IDs.
     # connectedCheck # Would try building the release version, that needs certificates
